// src/lib/LineChart.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import * as d3 from 'd3';
  
  // Interfaces
  interface HashtagData {
    hashtag: string;
    date: Date;
    count: number;
  }
  
  // Props
  export let data: HashtagData[] = [];
  export let chartTitle: string = "Hashtag Trends Over Time";
  export let xAxisLabel: string = "Months of the Year 2022";
  export let yAxisLabel: string = "Number of Tweets";
  
  let chartElement: SVGSVGElement;
  let containerElement: HTMLDivElement;
  let dimensions = { width: 0, height: 0 };
  let tooltip;
  
  // Group data by hashtag
  $: hashtagsGrouped = groupData(data);
  
  function groupData(inputData: HashtagData[]) {
    if (!inputData || inputData.length === 0) return [];
    
    const grouped = d3.group(inputData, d => d.hashtag);
    return Array.from(grouped, ([key, values]) => ({
      key,
      values
    }));
  }
  
  // Calculate scales and domains
  $: scales = calculateScales(data, dimensions);
  
  function calculateScales(inputData: HashtagData[], dims) {
    if (!inputData || inputData.length === 0 || dims.width === 0 || dims.height === 0) {
      return { xScale: null, yScale: null, colorScale: null, margin: null };
    }
    
    // Define margins with more space for title and legend
    const margin = { top: 40, right: 120, bottom: 50, left: 70 };
    const width = dims.width - margin.left - margin.right;
    const height = dims.height - margin.top - margin.bottom;
    
    // Create time scale for x-axis
    const dates = inputData.map(d => new Date(d.date));
    const xScale = d3.scaleTime()
      .domain(d3.extent(dates) as [Date, Date])
      .range([0, width]);
    
    // Create linear scale for y-axis
    const yScale = d3.scaleLinear()
      .domain([0, d3.max(inputData, d => d.count) || 0])
      .range([height, 0]);
    
    // Create color scale
    const hashtags = Array.from(new Set(inputData.map(d => d.hashtag)));
    const colorScale = d3.scaleOrdinal<string>()
      .domain(hashtags)
      .range(d3.quantize(
        t => d3.interpolateRainbow(t),
        hashtags.length > 0 ? hashtags.length : 1
      ));
    
    return { xScale, yScale, colorScale, margin, width, height };
  }
  
  function findClosestPoint(mouseX, mouseY) {
    if (!scales.xScale || !scales.yScale || !hashtagsGrouped.length) return null;
    
    let closestPoint = null;
    let minDistance = Infinity;
    
    hashtagsGrouped.forEach(group => {
      group.values.forEach(point => {
        const xPos = scales.xScale(new Date(point.date));
        const yPos = scales.yScale(point.count);
        const distance = Math.sqrt(
          Math.pow(xPos - mouseX, 2) + Math.pow(yPos - mouseY, 2)
        );
        
        if (distance < minDistance) {
          minDistance = distance;
          closestPoint = point;
        }
      });
    });
    
    return minDistance < 30 ? closestPoint : null; // 30px threshold for detection
  }
  
  function updateChart() {
    if (!data || data.length === 0 || !chartElement || 
        dimensions.width === 0 || dimensions.height === 0 || 
        !scales.xScale || !scales.yScale || !scales.colorScale) return;
    
    // Clear previous chart
    d3.select(chartElement).selectAll("*").remove();
    
    // Create SVG container
    const svg = d3.select(chartElement)
      .attr("width", dimensions.width)
      .attr("height", dimensions.height)
      .append("g")
      .attr("transform", `translate(${scales.margin.left},${scales.margin.top})`);
    
    // Add x-axis
    svg.append("g")
      .attr("transform", `translate(0,${scales.height})`)
      .call(d3.axisBottom(scales.xScale).ticks(5));
    
    // Add x-axis label
    svg.append("text")
      .attr("text-anchor", "middle")
      .attr("x", scales.width / 2)
      .attr("y", scales.height + 35)
      .style("font-size", "12px")
      .text(xAxisLabel);
    
    // Add y-axis
    svg.append("g")
      .call(d3.axisLeft(scales.yScale));
    
    // Add y-axis label
    svg.append("text")
      .attr("text-anchor", "middle")
      .attr("transform", "rotate(-90)")
      .attr("y", -45)
      .attr("x", -scales.height / 2)
      .style("font-size", "12px")
      .text(yAxisLabel);
    
    // Add chart title
    svg.append("text")
      .attr("text-anchor", "middle")
      .attr("x", scales.width / 2)
      .attr("y", -15)
      .style("font-size", "16px")
      .style("font-weight", "bold")
      .text(chartTitle);
    
    // Create tooltip
    tooltip = d3.select(containerElement)
      .append("div")
      .attr("class", "tooltip")
      .style("opacity", 0)
      .style("position", "absolute")
      .style("background-color", "white")
      .style("border", "1px solid #ddd")
      .style("border-radius", "8px")
      .style("padding", "10px")
      .style("pointer-events", "none")
      .style("font-size", "12px")
      .style("box-shadow", "0 4px 8px rgba(0,0,0,0.2)");
    
    // Add interaction area for tooltip
    svg.append("rect")
      .attr("width", scales.width)
      .attr("height", scales.height)
      .style("fill", "none")
      .style("pointer-events", "all")
      .on("mousemove", function(event) {
        const [mouseX, mouseY] = d3.pointer(event);
        const closestPoint = findClosestPoint(mouseX, mouseY);
        
        if (closestPoint) {
          const xPos = scales.xScale(new Date(closestPoint.date));
          const yPos = scales.yScale(closestPoint.count);
          
          // Update tooltip content and position
          tooltip
            .style("opacity", 1)
            .style("left", `${event.offsetX + 15}px`)
            .style("top", `${event.offsetY - 28}px`)
            .html(`<div style="display: flex; align-items: center; margin-bottom: 4px;">
                   <div style="width: 12px; height: 12px; background-color: ${scales.colorScale(
                     closestPoint.hashtag
                   )}; margin-right: 6px; border-radius: 50%;"></div>
                   <strong>${closestPoint.hashtag}</strong>
                 </div>
                 Date: ${new Date(closestPoint.date).toLocaleDateString()}<br/>
                 Count: ${closestPoint.count}`);
          
          // Add highlight circle
          svg.selectAll(".hover-circle").remove();
          svg.append("circle")
            .attr("class", "hover-circle")
            .attr("cx", xPos)
            .attr("cy", yPos)
            .attr("r", 5)
            .style("fill", scales.colorScale(closestPoint.hashtag))
            .style("stroke", "#fff")
            .style("stroke-width", 2);
        } else {
          tooltip.style("opacity", 0);
          svg.selectAll(".hover-circle").remove();
        }
      })
      .on("mouseleave", function() {
        tooltip.style("opacity", 0);
        svg.selectAll(".hover-circle").remove();
      });
    
    // Create line generator
    const lineGenerator = d3.line<HashtagData>()
      .x(d => scales.xScale(new Date(d.date)))
      .y(d => scales.yScale(d.count));
    
    // Draw lines
    svg.selectAll(".line")
      .data(hashtagsGrouped)
      .join("path")
      .attr("fill", "none")
      .attr("stroke", d => scales.colorScale(d.key))
      .attr("stroke-width", 1.5)
      .attr("d", d => lineGenerator(d.values));
    
    // Add legend
    const legend = svg.append("g")
      .attr("transform", `translate(${scales.width + 20}, 0)`);
    
    // Only show top 10 hashtags in legend if there are many
    const legendData = hashtagsGrouped.slice(0, 10);
    
    legend.selectAll(".legend-item")
      .data(legendData)
      .join("g")
      .attr("class", "legend-item")
      .attr("transform", (d, i) => `translate(0, ${i * 20})`)
      .call(g => {
        g.append("circle")
          .attr("r", 5)
          .attr("fill", d => scales.colorScale(d.key));
        
        g.append("text")
          .attr("x", 10)
          .attr("y", 5)
          .attr("font-size", "10px")
          .text(d => d.key.length > 15 ? d.key.substring(0, 15) + '...' : d.key);
      });
    
    if (hashtagsGrouped.length > 10) {
      legend.append("text")
        .attr("y", 10 * 20 + 10)
        .attr("font-size", "10px")
        .attr("font-style", "italic")
        .text(`+ ${hashtagsGrouped.length - 10} more`);
    }
  }
  
  // Update dimensions and recalculate chart when component mounts
  onMount(() => {
    if (containerElement) {
      const { width, height } = containerElement.getBoundingClientRect();
      dimensions = { width, height };
    }
  });
  
  // Update chart when data or dimensions change
  $: if (data && dimensions.width > 0 && dimensions.height > 0) {
    if (tooltip) {
      tooltip.remove();
      tooltip = null;
    }
    
    updateChart();
  }
</script>

<div bind:this={containerElement} class="w-full h-full relative">
  <svg bind:this={chartElement} width="100%" height="100%"></svg>
</div>

// client/src/components/line-chart.tsx
// @ts-nocheck

import React, {
  useEffect,
  useRef,
  useState,
  useMemo,
  useCallback,
} from "react";
import * as d3 from "d3";

// Improved TypeScript interfaces
interface HashtagData {
  hashtag: string;
  date: Date;
  count: number;
}

interface LineChartProps {
  data: HashtagData[];
}

interface Dimensions {
  width: number;
  height: number;
}
const LineChart: React.FC<LineChartProps> = ({ data }) => {
  const chartRef = useRef<SVGSVGElement | null>(null);
  const containerRef = useRef<HTMLDivElement | null>(null);
  const [dimensions, setDimensions] = useState<Dimensions>({
    width: 0,
    height: 0,
  });

  // Memoized function to get container dimensions
  const updateDimensions = useCallback(() => {
    if (containerRef.current) {
      const { width, height } = containerRef.current.getBoundingClientRect();
      setDimensions({ width, height });
    }
  }, []);

  // Effect to handle resize and get initial dimensions
  useEffect(() => {
    updateDimensions();

    const resizeObserver = new ResizeObserver(updateDimensions);
    if (containerRef.current) {
      resizeObserver.observe(containerRef.current);
    }

    // Cleanup
    return () => {
      if (containerRef.current) {
        resizeObserver.unobserve(containerRef.current);
      }
      resizeObserver.disconnect();
    };
  }, [updateDimensions]);

  // Memoize data grouping to avoid recalculation
  const hashtagsGrouped = useMemo(() => {
    if (!data || data.length === 0) return [];

    // Group data by hashtag
    const grouped = d3.group(data, (d) => d.hashtag);

    // Convert Map to Array for visualization compatibility
    return Array.from(grouped, ([key, values]) => ({
      key,
      values,
    }));
  }, [data]);

  // Memoize scales and domains
  const { xScale, yScale, colorScale } = useMemo(() => {
    if (
      !data ||
      data.length === 0 ||
      dimensions.width === 0 ||
      dimensions.height === 0
    ) {
      return { xScale: null, yScale: null, colorScale: null, dates: [] };
    }

    const margin = { top: 10, right: 30, bottom: 30, left: 60 };
    const width = dimensions.width - margin.left - margin.right;
    const height = dimensions.height - margin.top - margin.bottom;

    // Extract dates and create time scale
    const dates = data.map((d) => new Date(d.date));
    const xScale = d3
      .scaleTime()
      .domain(d3.extent(dates) as [Date, Date])
      .range([0, width]);

    // Create linear scale for y-axis
    const yScale = d3
      .scaleLinear()
      .domain([0, d3.max(data, (d) => d.count) || 0])
      .range([height, 0]);

    // Create color scale
    const hashtags = Array.from(new Set(data.map((d) => d.hashtag)));
    const colorScale = d3
      .scaleOrdinal<string>()
      .domain(hashtags)
      .range(
        d3.quantize(
          (t) => d3.interpolateRainbow(t),
          hashtags.length > 0 ? hashtags.length : 1
        )
      );

    return { xScale, yScale, colorScale, dates, margin };
  }, [data, dimensions.width, dimensions.height]);

  // Memoized function to find closest point to mouse position
  const findClosestPoint = useCallback(
    (mouseX: number, mouseY: number) => {
      if (!xScale || !yScale || !hashtagsGrouped.length) return null;

      let closestPoint: HashtagData | null = null;
      let minDistance = Infinity;

      hashtagsGrouped.forEach((group) => {
        group.values.forEach((point) => {
          const xPos = xScale(new Date(point.date));
          const yPos = yScale(point.count);
          const distance = Math.sqrt(
            Math.pow(xPos - mouseX, 2) + Math.pow(yPos - mouseY, 2)
          );

          if (distance < minDistance) {
            minDistance = distance;
            closestPoint = point;
          }
        });
      });

      return minDistance < 30 ? closestPoint : null; // 30px threshold for detection
    },
    [xScale, yScale, hashtagsGrouped]
  );

  // Effect to draw the chart
  useEffect(() => {
    if (
      !data ||
      data.length === 0 ||
      !chartRef.current ||
      dimensions.width === 0 ||
      dimensions.height === 0 ||
      !xScale ||
      !yScale ||
      !colorScale
    )
      return;

    // Clear previous chart if exists
    d3.select(chartRef.current).selectAll("*").remove();

    // Configure margins and dimensions
    const margin = { top: 10, right: 30, bottom: 30, left: 60 };
    const width = dimensions.width - margin.left - margin.right;
    const height = dimensions.height - margin.top - margin.bottom;

    // Create SVG container
    const svg = d3
      .select(chartRef.current)
      .attr("width", dimensions.width)
      .attr("height", dimensions.height)
      .append("g")
      .attr("transform", `translate(${margin.left},${margin.top})`);

    // Add X axis
    svg
      .append("g")
      .attr("transform", `translate(0,${height})`)
      .call(d3.axisBottom(xScale).ticks(5));

    // Add Y axis
    svg.append("g").call(d3.axisLeft(yScale));

    // Create a tooltip div with memoized styles
    const tooltip = d3
      .select(containerRef.current)
      .append("div")
      .attr("class", "tooltip")
      .style("opacity", 0)
      .style("position", "absolute")
      .style("background-color", "white")
      .style("border", "1px solid #ddd")
      .style("border-radius", "8px")
      .style("padding", "10px")
      .style("pointer-events", "none")
      .style("font-size", "12px")
      .style("box-shadow", "0 4px 8px rgba(0,0,0,0.2)");

    // Create the tooltip interaction area
    svg
      .append("rect")
      .attr("width", width)
      .attr("height", height)
      .style("fill", "none")
      .style("pointer-events", "all")
      .on("mousemove", function (event) {
        const [mouseX, mouseY] = d3.pointer(event);
        const closestPoint = findClosestPoint(mouseX, mouseY);

        if (closestPoint) {
          const xPos = xScale(new Date(closestPoint.date));
          const yPos = yScale(closestPoint.count);

          // Update tooltip content and position with color indicator
          tooltip
            .style("opacity", 1)
            .style("left", `${event.offsetX + 15}px`)
            .style("top", `${event.offsetY - 28}px`)
            .html(`<div style="display: flex; align-items: center; margin-bottom: 4px;">
                     <div style="width: 12px; height: 12px; background-color: ${colorScale(
                       closestPoint.hashtag
                     )}; margin-right: 6px; border-radius: 50%;"></div>
                     <strong>${closestPoint.hashtag}</strong>
                   </div>
                   Date: ${new Date(
                     closestPoint.date
                   ).toLocaleDateString()}<br/>
                   Count: ${closestPoint.count}`);

          // Add highlight circle
          svg.selectAll(".hover-circle").remove();
          svg
            .append("circle")
            .attr("class", "hover-circle")
            .attr("cx", xPos)
            .attr("cy", yPos)
            .attr("r", 5)
            .style("fill", colorScale(closestPoint.hashtag))
            .style("stroke", "#fff")
            .style("stroke-width", 2);
        } else {
          // Hide tooltip when not over any point
          tooltip.style("opacity", 0);
          svg.selectAll(".hover-circle").remove();
        }
      })
      .on("mouseleave", function () {
        // Hide tooltip and highlight when mouse leaves chart area
        tooltip.style("opacity", 0);
        svg.selectAll(".hover-circle").remove();
      });

    // Create line generator once
    const lineGenerator = d3
      .line<HashtagData>()
      .x((d) => xScale(new Date(d.date)))
      .y((d) => yScale(d.count));

    // Draw the lines
    svg
      .selectAll(".line")
      .data(hashtagsGrouped)
      .join("path")
      .attr("fill", "none")
      .attr("stroke", (d) => colorScale(d.key))
      .attr("stroke-width", 1.5)
      .attr("d", (d) => lineGenerator(d.values));

    // Cleanup
    return () => {
      tooltip.remove();
    };
  }, [
    data,
    dimensions,
    xScale,
    yScale,
    colorScale,
    hashtagsGrouped,
    findClosestPoint,
  ]);

  return (
    <div ref={containerRef} className="w-full h-full relative">
      <svg ref={chartRef} width="100%" height="100%"></svg>
    </div>
  );
};

export default LineChart;
